# Generated by Django 5.0.6 on 2024-06-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('captcha', models.CharField(max_length=4)),
            ],
        ),
    ]
