# Generated by Django 5.0.6 on 2024-06-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlauth', '0002_alter_captchamodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
